@startuml

package GoldenPhenix #DDDDDD
{
    Castle <-- Room
    Castle <-- Player
    Castle <-- Bat

    Door <.. Object

    ItemStack <-- Object

    Room <-- Door
    Room <.. Object
    Room <.. Exception
    Room <-- Vector2

    Player #-- Entity
    Player <-- ItemStack

    Bat #-- Entity

    Entity <-- Vector2

    class Castle
    class Room
    class Player < extends Entity >
    class Bat < extends Entity >
    class Door
    class ItemStack
    class Object
    class Entity
    class Exception< extends std::runtime_error >
    class Vector2< T >
}

package "GoldenPhenix_SDL2" #DDAADD
{
    Graphics <.. Exception

    GameManager <-- ScreensManager
    GameManager <-- Timer

    AudioManager <.. Exception

    MainScreen <-- Castle
    MainScreen #-- GameEntity
    MainScreen <-- AnimatedTexture

    ShopScreen #-- GameEntity
    ShopScreen <-- Castle

    StartScreen #-- Texture

    ScreensManager <-- MainScreen
    ScreensManager <-- ShopScreen
    ScreensManager <-- StartScreen
    ScreensManager <-- AudioManager

    AnimatedTexture <-- Timer
    AnimatedTexture #-- Texture

    Texture #-- GameEntity
    Texture <-- Graphics

    GameEntity #-- Entity



    class Graphics
    class GameManager
    class AudioManager<< (S, #FF7700) >>
    class Timer
    class MainScreen< extends GameEntity >
    class ScreensManager
    class ShopScreen< extends GameEntity >
    class StartScreen< extends Texture >
    class AnimatedTexture < extends Texture >
    class GameEntity < extends Entity >
    class Texture < extends GameEntity >
}

@enduml
